server:
  port: 13000

spring:
  application:
    name: gateway-api
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        ephemeral: false
    gateway:
      routes:
        ## order服务前缀匹配路由
        - id: order-api
          uri: lb://order-api
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        ## inventory服务前缀匹配路由
        - id: inventory-api
          uri: lb://inventory-api
          predicates:
            - Path=/inventory/**
          filters:
            - StripPrefix=1
        ## product服务前缀匹配路由
        - id: product-api
          uri: lb://product-api
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        ## user服务前缀匹配路由
        - id: user-api
          uri: lb://user-api
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1